/* lld_pmu.h -- Auto-generated LLD for PMU (from sfr_pmu.h) */
/* DO NOT EDIT: Regenerated by generate_pmu_lld.py from old SFR */
#ifndef LLD_PMU_H
#define LLD_PMU_H

#include <stdint.h>
#include "sfr_pmu.h"

/* === BEGIN LLD_PMU === */

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: PMU_CON                        offset=0x0000
 * 
 * SRC_SHA: 5a19a6061a49342e
 * ═══════════════════════════════════════════════════════════════ */

/** @brief DMA enable */
static inline uint8_t PMU_PMU_CON_DMA_EN_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000001U) >> 0U);
}

/** @brief DMA enable */
static inline void PMU_PMU_CON_DMA_EN_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[0];
    r &= ~0x00000001U;
    r |= ((uint32_t)val << 0U) & 0x00000001U;
    base[0] = r;
}

/** @brief DMA pass status */
static inline uint8_t PMU_PMU_CON_DMA_PASS_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000002U) >> 1U);
}

/** @brief HCPU reset control */
static inline uint8_t PMU_PMU_CON_HCPU_RST_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000004U) >> 2U);
}

/** @brief HCPU reset control */
static inline void PMU_PMU_CON_HCPU_RST_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[0];
    r &= ~0x00000004U;
    r |= ((uint32_t)val << 2U) & 0x00000004U;
    base[0] = r;
}

/** @brief HCPU vector init */
static inline uint8_t PMU_PMU_CON_HCPU_VINIT_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000008U) >> 3U);
}

/** @brief HCPU vector init */
static inline void PMU_PMU_CON_HCPU_VINIT_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[0];
    r &= ~0x00000008U;
    r |= ((uint32_t)val << 3U) & 0x00000008U;
    base[0] = r;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: STATUS_CON                     offset=0x0004
 * 
 * SRC_SHA: 10c4476019d6431f
 * ═══════════════════════════════════════════════════════════════ */

/** @brief DMA done flag */
static inline uint8_t PMU_STATUS_CON_DONE_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000001U) >> 0U);
}

/** @brief DMA done flag */
static inline void PMU_STATUS_CON_DONE_clear(volatile uint32_t *base)
{
    base[1] = 0x00000001U; /* W1C: write 1 to clear */
}

/** @brief DMA error flag */
static inline uint8_t PMU_STATUS_CON_ERR_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000004U) >> 2U);
}

/** @brief DMA fail flag */
static inline uint8_t PMU_STATUS_CON_FAIL_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000002U) >> 1U);
}

/** @brief FIFO level indicator */
static inline uint8_t PMU_STATUS_CON_LEVEL_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000180U) >> 7U);
}

/** @brief FIFO level indicator */
static inline void PMU_STATUS_CON_LEVEL_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[1];
    r &= ~0x00000180U;
    r |= ((uint32_t)val << 7U) & 0x00000180U;
    base[1] = r;
}

/** @brief Threshold level 4-bit */
static inline uint8_t PMU_STATUS_CON_THRESH_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000078U) >> 3U);
}

/** @brief Threshold level 4-bit */
static inline void PMU_STATUS_CON_THRESH_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[1];
    r &= ~0x00000078U;
    r |= ((uint32_t)val << 3U) & 0x00000078U;
    base[1] = r;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: CLK_CON                        offset=0x0008
 * 
 * SRC_SHA: 0cf7c2dc18c04987
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Clock divider ratio */
static inline uint8_t PMU_CLK_CON_CLK_DIV_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x0000001EU) >> 1U);
}

/** @brief Clock divider ratio */
static inline void PMU_CLK_CON_CLK_DIV_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x0000001EU;
    r |= ((uint32_t)val << 1U) & 0x0000001EU;
    base[2] = r;
}

/** @brief Clock enable signal */
static inline uint8_t PMU_CLK_CON_CLK_EN_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x00000001U) >> 0U);
}

/** @brief Clock enable signal */
static inline void PMU_CLK_CON_CLK_EN_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x00000001U;
    r |= ((uint32_t)val << 0U) & 0x00000001U;
    base[2] = r;
}

/** @brief Power gate control */
static inline uint8_t PMU_CLK_CON_CLK_GATE_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x00000080U) >> 7U);
}

/** @brief Power gate control */
static inline void PMU_CLK_CON_CLK_GATE_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x00000080U;
    r |= ((uint32_t)val << 7U) & 0x00000080U;
    base[2] = r;
}

/** @brief Clock source select signal */
static inline uint8_t PMU_CLK_CON_CLK_SEL_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x00000060U) >> 5U);
}

/** @brief Clock source select signal */
static inline void PMU_CLK_CON_CLK_SEL_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x00000060U;
    r |= ((uint32_t)val << 5U) & 0x00000060U;
    base[2] = r;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: SWT_CON                        offset=0x000C
 * 
 * SRC_SHA: 8eab0d8c3aa15c13
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Software timer reload value */
static inline uint16_t PMU_SWT_CON_SCALL_get(volatile uint32_t *base)
{
    return (uint16_t)((base[3] & 0xFFFF0000U) >> 16U);
}

/** @brief Software timer reload value */
static inline void PMU_SWT_CON_SCALL_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[3];
    r &= ~0xFFFF0000U;
    r |= ((uint32_t)val << 16U) & 0xFFFF0000U;
    base[3] = r;
}

/** @brief Software timer prescaler */
static inline uint16_t PMU_SWT_CON_SCPRE_get(volatile uint32_t *base)
{
    return (uint16_t)((base[3] & 0x0000FFFFU) >> 0U);
}

/** @brief Software timer prescaler */
static inline void PMU_SWT_CON_SCPRE_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[3];
    r &= ~0x0000FFFFU;
    r |= ((uint32_t)val << 0U) & 0x0000FFFFU;
    base[3] = r;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: RST_CON                        offset=0x0010
 * 
 * SRC_SHA: 355981e0ba1f75b1
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Retention control register */
static inline uint32_t PMU_RST_CON_RET_CON_get(volatile uint32_t *base)
{
    return (uint32_t)((base[4] & 0xFFFFFFFFU) >> 0U);
}

/** @brief Retention control register */
static inline void PMU_RST_CON_RET_CON_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[4];
    r &= ~0xFFFFFFFFU;
    r |= ((uint32_t)val << 0U) & 0xFFFFFFFFU;
    base[4] = r;
}

/* === END LLD_PMU === */

#endif /* LLD_PMU_H */
