/* lld_pmu.h -- Auto-generated LLD for PMU
 * Generated by: tests/workspace_demo/generate_pmu_lld.py
 * Source SFR  : old_sfr/sfr_pmu.h
 * DO NOT EDIT -- regenerate with generate_pmu_lld.py
 */
#ifndef LLD_PMU_H
#define LLD_PMU_H

#include <stdint.h>
#include "sfr_pmu.h"

/* === BEGIN LLD_PMU === */

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: PMU_CON                        offset=0x0000
 * 
 * SRC_SHA: 5a19a6061a49342e
 * ═══════════════════════════════════════════════════════════════ */

/** @brief DMA enable */
static inline uint8_t lld_pmu_pmu_con_dma_en_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stPMU_CTRL.stNative.DMA_EN);
}

/** @brief DMA enable */
static inline void lld_pmu_pmu_con_dma_en_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stPMU_CTRL.stNative.DMA_EN = val;
}

/** @brief DMA pass status */
static inline uint8_t lld_pmu_pmu_con_dma_pass_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stPMU_CTRL.stNative.DMA_PASS);
}

/** @brief HCPU reset control */
static inline uint8_t lld_pmu_pmu_con_hcpu_rst_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stPMU_CTRL.stNative.HCPU_RST);
}

/** @brief HCPU reset control */
static inline void lld_pmu_pmu_con_hcpu_rst_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stPMU_CTRL.stNative.HCPU_RST = val;
}

/** @brief HCPU vector init */
static inline uint8_t lld_pmu_pmu_con_hcpu_vinit_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stPMU_CTRL.stNative.HCPU_VINIT);
}

/** @brief HCPU vector init */
static inline void lld_pmu_pmu_con_hcpu_vinit_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stPMU_CTRL.stNative.HCPU_VINIT = val;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: STATUS_CON                     offset=0x0004
 * 
 * SRC_SHA: 10c4476019d6431f
 * ═══════════════════════════════════════════════════════════════ */

/** @brief DMA done flag */
static inline uint8_t lld_pmu_status_con_done_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stSTATUS_CON.stNative.COMPLETE);
}

/** @brief DMA done flag */
static inline void lld_pmu_status_con_done_clear(struct lld_pmu *lld)
{
    lld->pSFR->stSTATUS_CON.stNative.COMPLETE = 1U; /* W1C: write 1 to clear */
}

/** @brief DMA error flag */
static inline uint8_t lld_pmu_status_con_err_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stSTATUS_CON.stNative.ERR);
}

/** @brief DMA fail flag */
static inline uint8_t lld_pmu_status_con_fail_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stSTATUS_CON.stNative.FAIL);
}

/** @brief FIFO level indicator */
static inline uint8_t lld_pmu_status_con_level_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stSTATUS_CON.stNative.LEVEL);
}

/** @brief FIFO level indicator */
static inline void lld_pmu_status_con_level_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stSTATUS_CON.stNative.LEVEL = val;
}

/** @brief Threshold level 4-bit */
static inline uint8_t lld_pmu_status_con_thresh_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stSTATUS_CON.stNative.THRESH);
}

/** @brief Threshold level 4-bit */
static inline void lld_pmu_status_con_thresh_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stSTATUS_CON.stNative.THRESH = val;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: CLK_CON                        offset=0x0008
 * 
 * SRC_SHA: 0cf7c2dc18c04987
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Clock divider ratio */
static inline uint8_t lld_pmu_clk_con_clk_div_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stCLK_CON.stNative.CLK_DIV);
}

/** @brief Clock divider ratio */
static inline void lld_pmu_clk_con_clk_div_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stCLK_CON.stNative.CLK_DIV = val;
}

/** @brief Clock enable signal */
static inline uint8_t lld_pmu_clk_con_clk_en_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stCLK_CON.stNative.CLK_EN);
}

/** @brief Clock enable signal */
static inline void lld_pmu_clk_con_clk_en_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stCLK_CON.stNative.CLK_EN = val;
}

/** @brief Power gate control */
static inline uint8_t lld_pmu_clk_con_clk_gate_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stCLK_CON.stNative.CLK_GATE);
}

/** @brief Power gate control */
static inline void lld_pmu_clk_con_clk_gate_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stCLK_CON.stNative.CLK_GATE = val;
}

/** @brief Clock source select signal */
static inline uint8_t lld_pmu_clk_con_clk_sel_get(struct lld_pmu *lld)
{
    return (uint8_t)(lld->pSFR->stCLK_CON.stNative.CLK_SEL);
}

/** @brief Clock source select signal */
static inline void lld_pmu_clk_con_clk_sel_set(struct lld_pmu *lld, uint8_t val)
{
    lld->pSFR->stCLK_CON.stNative.CLK_SEL = val;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: SWT_CON                        offset=0x000C
 * 
 * SRC_SHA: 8eab0d8c3aa15c13
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Software timer reload value */
static inline uint16_t lld_pmu_swt_con_scall_get(struct lld_pmu *lld)
{
    return (uint16_t)(lld->pSFR->stSWT_CON.stNative.SCALL);
}

/** @brief Software timer reload value */
static inline void lld_pmu_swt_con_scall_set(struct lld_pmu *lld, uint16_t val)
{
    lld->pSFR->stSWT_CON.stNative.SCALL = val;
}

/** @brief Software timer prescaler */
static inline uint16_t lld_pmu_swt_con_scpre_get(struct lld_pmu *lld)
{
    return (uint16_t)(lld->pSFR->stSWT_CON.stNative.SCPRE);
}

/** @brief Software timer prescaler */
static inline void lld_pmu_swt_con_scpre_set(struct lld_pmu *lld, uint16_t val)
{
    lld->pSFR->stSWT_CON.stNative.SCPRE = val;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: RST_CON                        offset=0x0010
 * 
 * SRC_SHA: 355981e0ba1f75b1
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Retention control register */
static inline uint32_t lld_pmu_rst_con_ret_con_get(struct lld_pmu *lld)
{
    return (uint32_t)(lld->pSFR->stRST_CON.stNative.RET_CON);
}

/** @brief Retention control register */
static inline void lld_pmu_rst_con_ret_con_set(struct lld_pmu *lld, uint32_t val)
{
    lld->pSFR->stRST_CON.stNative.RET_CON = val;
}

/* === END LLD_PMU === */

#endif /* LLD_PMU_H */