/* lld_pmu.h -- Auto-generated LLD for PMU
 * Generated by: tests/workspace_demo/generate_pmu_lld.py
 * Source SFR  : old_sfr/sfr_pmu.h
 * DO NOT EDIT -- regenerate with generate_pmu_lld.py
 */
#ifndef LLD_PMU_H
#define LLD_PMU_H

#include <stdint.h>
#include "sfr_pmu.h"

/* === BEGIN LLD_PMU === */

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: PMU_CTRL                        offset=0x0000
 * 
 * SRC_SHA: 5a19a6061a49342e
 * ═══════════════════════════════════════════════════════════════ */

/** @brief DMA enable */
static inline uint8_t lld_pmu_pmu_ctrl_dma_en_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000001U) >> 0U);
}

/** @brief DMA enable */
static inline void lld_pmu_pmu_ctrl_dma_en_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[0];
    r &= ~0x00000001U;
    r |= ((uint32_t)val << 0U) & 0x00000001U;
    base[0] = r;
}

/** @brief DMA pass status */
static inline uint8_t lld_pmu_pmu_ctrl_dma_pass_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000002U) >> 1U);
}

/** @brief HCPU reset control */
static inline uint8_t lld_pmu_pmu_ctrl_hcpu_rst_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000004U) >> 2U);
}

/** @brief HCPU reset control */
static inline void lld_pmu_pmu_ctrl_hcpu_rst_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[0];
    r &= ~0x00000004U;
    r |= ((uint32_t)val << 2U) & 0x00000004U;
    base[0] = r;
}

/** @brief HCPU vector init */
static inline uint8_t lld_pmu_pmu_ctrl_hcpu_vinit_get(volatile uint32_t *base)
{
    return (uint8_t)((base[0] & 0x00000008U) >> 3U);
}

/** @brief HCPU vector init */
static inline void lld_pmu_pmu_ctrl_hcpu_vinit_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[0];
    r &= ~0x00000008U;
    r |= ((uint32_t)val << 3U) & 0x00000008U;
    base[0] = r;
}

/* ═══════════════════════════════════════════════════════════════
 * REGISTER: STATUS_CON                     offset=0x0004
 * 
 * SRC_SHA: 29f32a36c9e24472
 * ═══════════════════════════════════════════════════════════════ */

/** @brief DMA done flag */
static inline uint8_t lld_pmu_status_con_complete_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000001U) >> 0U);
}

/** @brief DMA done flag */
static inline void lld_pmu_status_con_complete_clear(volatile uint32_t *base)
{
    base[1] = 0x00000001U; /* W1C: write 1 to clear */
}

/** @brief DMA abort status */
static inline uint8_t lld_pmu_status_con_abort_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000200U) >> 9U);
}

/** @brief DMA abort status */
static inline void lld_pmu_status_con_abort_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[1];
    r &= ~0x00000200U;
    r |= ((uint32_t)val << 9U) & 0x00000200U;
    base[1] = r;
}

/** @brief DMA error flag */
static inline uint8_t lld_pmu_status_con_err_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000004U) >> 2U);
}

/** @brief DMA error flag */
static inline void lld_pmu_status_con_err_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[1];
    r &= ~0x00000004U;
    r |= ((uint32_t)val << 2U) & 0x00000004U;
    base[1] = r;
}

/** @brief FIFO level indicator */
static inline uint8_t lld_pmu_status_con_level_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x00000600U) >> 9U);
}

/** @brief FIFO level indicator */
static inline void lld_pmu_status_con_level_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[1];
    r &= ~0x00000600U;
    r |= ((uint32_t)val << 9U) & 0x00000600U;
    base[1] = r;
}

/** @brief Threshold level 4-bit */
static inline uint8_t lld_pmu_status_con_thresh_get(volatile uint32_t *base)
{
    return (uint8_t)((base[1] & 0x000000F8U) >> 3U);
}

/** @brief Threshold level 4-bit */
static inline void lld_pmu_status_con_thresh_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[1];
    r &= ~0x000000F8U;
    r |= ((uint32_t)val << 3U) & 0x000000F8U;
    base[1] = r;
}
/* ═══════════════════════════════════════════════════════════════
 * REGISTER: CLK_CON                        offset=0x0008
 * 
 * SRC_SHA: eb08a01c1bdf1630
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Clock divider ratio */
static inline uint8_t lld_pmu_clk_con_clk_div_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x0000001EU) >> 1U);
}

/** @brief Clock divider ratio */
static inline void lld_pmu_clk_con_clk_div_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x0000001EU;
    r |= ((uint32_t)val << 1U) & 0x0000001EU;
    base[2] = r;
}

/** @brief Clock enable signal */
static inline uint8_t lld_pmu_clk_con_clk_en_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x00000001U) >> 0U);
}

/** @brief Clock enable signal */
static inline void lld_pmu_clk_con_clk_en_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x00000001U;
    r |= ((uint32_t)val << 0U) & 0x00000001U;
    base[2] = r;
}

/** @brief Power gate status (read-only in v2) */
static inline uint8_t lld_pmu_clk_con_clk_gate_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x00000080U) >> 7U);
}

/** @brief Clock source mux: 0=PLL0 1=PLL1 2=OSC 3=EXT */
static inline uint8_t lld_pmu_clk_con_clk_sel_get(volatile uint32_t *base)
{
    return (uint8_t)((base[2] & 0x00000060U) >> 5U);
}

/** @brief Clock source mux: 0=PLL0 1=PLL1 2=OSC 3=EXT */
static inline void lld_pmu_clk_con_clk_sel_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[2];
    r &= ~0x00000060U;
    r |= ((uint32_t)val << 5U) & 0x00000060U;
    base[2] = r;
}
/* ═══════════════════════════════════════════════════════════════
 * REGISTER: RST_CON                        offset=0x0010
 * 
 * SRC_SHA: 355981e0ba1f75b1
 * ═══════════════════════════════════════════════════════════════ */

/** @brief Retention control register */
static inline uint32_t lld_pmu_rst_con_ret_con_get(volatile uint32_t *base)
{
    return (uint32_t)((base[4] & 0xFFFFFFFFU) >> 0U);
}

/** @brief Retention control register */
static inline void lld_pmu_rst_con_ret_con_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[4];
    r &= ~0xFFFFFFFFU;
    r |= ((uint32_t)val << 0U) & 0xFFFFFFFFU;
    base[4] = r;
}

/* === END LLD_PMU === */


/* ═══════════════════════════════════════════════════════════════
 * REGISTER: IRQ_CON                        offset=0x0010
 * 
 * SRC_SHA: d1d0723d0ea2949d
 * ═══════════════════════════════════════════════════════════════ */

/** @brief IRQ enable */
static inline uint8_t lld_pmu_irq_con_irq_en_get(volatile uint32_t *base)
{
    return (uint8_t)((base[4] & 0x00000001U) >> 0U);
}

/** @brief IRQ enable */
static inline void lld_pmu_irq_con_irq_en_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[4];
    r &= ~0x00000001U;
    r |= ((uint32_t)val << 0U) & 0x00000001U;
    base[4] = r;
}

static inline void lld_pmu_irq_con_irq_en_irq_enable(volatile uint32_t *base)  { base[4] |=  0x00000001U; }
static inline void lld_pmu_irq_con_irq_en_irq_disable(volatile uint32_t *base) { base[4] &= ~0x00000001U; }
static inline uint32_t lld_pmu_irq_con_irq_en_irq_status(volatile uint32_t *base) { return (base[4] & 0x00000001U); }
static inline void lld_pmu_irq_con_irq_en_irq_clear(volatile uint32_t *base)   { base[4] = 0x00000001U; }

/** @brief IRQ mask bits */
static inline uint8_t lld_pmu_irq_con_irq_mask_get(volatile uint32_t *base)
{
    return (uint8_t)((base[4] & 0x0000000CU) >> 2U);
}

/** @brief IRQ mask bits */
static inline void lld_pmu_irq_con_irq_mask_set(volatile uint32_t *base, uint32_t val)
{
    uint32_t r = base[4];
    r &= ~0x0000000CU;
    r |= ((uint32_t)val << 2U) & 0x0000000CU;
    base[4] = r;
}

static inline void lld_pmu_irq_con_irq_mask_irq_enable(volatile uint32_t *base)  { base[4] |=  0x0000000CU; }
static inline void lld_pmu_irq_con_irq_mask_irq_disable(volatile uint32_t *base) { base[4] &= ~0x0000000CU; }
static inline uint32_t lld_pmu_irq_con_irq_mask_irq_status(volatile uint32_t *base) { return (base[4] & 0x0000000CU); }
static inline void lld_pmu_irq_con_irq_mask_irq_clear(volatile uint32_t *base)   { base[4] = 0x0000000CU; }

/** @brief IRQ pending flag */
static inline uint8_t lld_pmu_irq_con_irq_pend_get(volatile uint32_t *base)
{
    return (uint8_t)((base[4] & 0x00000002U) >> 1U);
}

/** @brief IRQ pending flag */
static inline void lld_pmu_irq_con_irq_pend_clear(volatile uint32_t *base)
{
    base[4] = 0x00000002U; /* W1C: write 1 to clear */
}

static inline void lld_pmu_irq_con_irq_pend_irq_enable(volatile uint32_t *base)  { base[4] |=  0x00000002U; }
static inline void lld_pmu_irq_con_irq_pend_irq_disable(volatile uint32_t *base) { base[4] &= ~0x00000002U; }
static inline uint32_t lld_pmu_irq_con_irq_pend_irq_status(volatile uint32_t *base) { return (base[4] & 0x00000002U); }
static inline void lld_pmu_irq_con_irq_pend_irq_clear(volatile uint32_t *base)   { base[4] = 0x00000002U; }

#endif /* LLD_PMU_H */
