/* AUTO-GENERATED by lld_gen — DO NOT EDIT */
#include <stdint.h>
#include <assert.h>
#include "sfr_pmu.h"
#include "lld_pmu.h"

static void test_lld_pmu_status_con_abort_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0x00000200U;
    uint32_t v = (uint32_t)lld_pmu_status_con_abort_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_status_con_abort_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0xFFFFFFFFU;
    lld_pmu_status_con_abort_set(regs, 0U);
    assert((regs[1] & 0x00000200U) == 0U);
    assert((regs[1] & ~0x00000200U) == (~0x00000200U & 0xFFFFFFFFU));
}

static void test_lld_pmu_status_con_err_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0x00000004U;
    uint32_t v = (uint32_t)lld_pmu_status_con_err_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_status_con_err_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0xFFFFFFFFU;
    lld_pmu_status_con_err_set(regs, 0U);
    assert((regs[1] & 0x00000004U) == 0U);
    assert((regs[1] & ~0x00000004U) == (~0x00000004U & 0xFFFFFFFFU));
}

static void test_lld_pmu_status_con_level_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0x00000200U;
    uint32_t v = (uint32_t)lld_pmu_status_con_level_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_status_con_level_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0xFFFFFFFFU;
    lld_pmu_status_con_level_set(regs, 0U);
    assert((regs[1] & 0x00000600U) == 0U);
    assert((regs[1] & ~0x00000600U) == (~0x00000600U & 0xFFFFFFFFU));
}

static void test_lld_pmu_status_con_thresh_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0x00000008U;
    uint32_t v = (uint32_t)lld_pmu_status_con_thresh_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_status_con_thresh_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0xFFFFFFFFU;
    lld_pmu_status_con_thresh_set(regs, 0U);
    assert((regs[1] & 0x000000F8U) == 0U);
    assert((regs[1] & ~0x000000F8U) == (~0x000000F8U & 0xFFFFFFFFU));
}

static void test_lld_pmu_clk_con_clk_gate_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[2] = 0x00000080U;
    uint32_t v = (uint32_t)lld_pmu_clk_con_clk_gate_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_clk_con_clk_sel_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[2] = 0x00000020U;
    uint32_t v = (uint32_t)lld_pmu_clk_con_clk_sel_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_clk_con_clk_sel_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[2] = 0xFFFFFFFFU;
    lld_pmu_clk_con_clk_sel_set(regs, 0U);
    assert((regs[2] & 0x00000060U) == 0U);
    assert((regs[2] & ~0x00000060U) == (~0x00000060U & 0xFFFFFFFFU));
}

static void test_lld_pmu_irq_con_irq_en_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[4] = 0x00000001U;
    uint32_t v = (uint32_t)lld_pmu_irq_con_irq_en_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_irq_con_irq_en_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[4] = 0xFFFFFFFFU;
    lld_pmu_irq_con_irq_en_set(regs, 0U);
    assert((regs[4] & 0x00000001U) == 0U);
    assert((regs[4] & ~0x00000001U) == (~0x00000001U & 0xFFFFFFFFU));
}

static void test_lld_pmu_irq_con_irq_pend_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[4] = 0x00000002U;
    uint32_t v = (uint32_t)lld_pmu_irq_con_irq_pend_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_irq_con_irq_pend_clear(void) {
    volatile uint32_t regs[256] = {0};
    lld_pmu_irq_con_irq_pend_clear(regs);
    assert(regs[4] == 0x00000002U);
}

static void test_lld_pmu_irq_con_irq_mask_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[4] = 0x00000004U;
    uint32_t v = (uint32_t)lld_pmu_irq_con_irq_mask_get(regs);
    assert(v == 1U);
}

static void test_lld_pmu_irq_con_irq_mask_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[4] = 0xFFFFFFFFU;
    lld_pmu_irq_con_irq_mask_set(regs, 0U);
    assert((regs[4] & 0x0000000CU) == 0U);
    assert((regs[4] & ~0x0000000CU) == (~0x0000000CU & 0xFFFFFFFFU));
}

int main(void) {
    test_lld_pmu_status_con_abort_get();
    test_lld_pmu_status_con_err_get();
    test_lld_pmu_status_con_level_get();
    test_lld_pmu_status_con_thresh_get();
    test_lld_pmu_clk_con_clk_gate_get();
    test_lld_pmu_clk_con_clk_sel_get();
    test_lld_pmu_irq_con_irq_en_get();
    test_lld_pmu_irq_con_irq_pend_get();
    test_lld_pmu_irq_con_irq_mask_get();
    return 0;
}
