/* AUTO-GENERATED by lld_gen -- DO NOT EDIT */
/* Coverage: ALL fields */
#include <stdint.h>
#include <assert.h>
#include "sfr_clk.h"
#include "lld_clk.h"

static void test_lld_clk_clk_con_clk_div_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_CON.stNative.CLK_DIV = 1U;
    assert(lld_clk_clk_con_clk_div_get(&lld) == 1U);
}

static void test_lld_clk_clk_con_clk_div_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_clk_con_clk_div_set(&lld, 1U);
    assert(sfr.stCLK_CON.stNative.CLK_DIV == 1U);
}

static void test_lld_clk_clk_con_clk_en_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_CON.stNative.CLK_EN = 1U;
    assert(lld_clk_clk_con_clk_en_get(&lld) == 1U);
}

static void test_lld_clk_clk_con_clk_en_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_clk_con_clk_en_set(&lld, 1U);
    assert(sfr.stCLK_CON.stNative.CLK_EN == 1U);
}

static void test_lld_clk_clk_con_clk_gate_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_CON.stNative.CLK_GATE = 1U;
    assert(lld_clk_clk_con_clk_gate_get(&lld) == 1U);
}

static void test_lld_clk_clk_con_clk_gate_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_clk_con_clk_gate_set(&lld, 1U);
    assert(sfr.stCLK_CON.stNative.CLK_GATE == 1U);
}

static void test_lld_clk_clk_con_clk_mode_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_CON.stNative.CLK_MODE = 1U;
    assert(lld_clk_clk_con_clk_mode_get(&lld) == 1U);
}

static void test_lld_clk_clk_con_clk_src_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_CON.stNative.CLK_SRC = 1U;
    assert(lld_clk_clk_con_clk_src_get(&lld) == 1U);
}

static void test_lld_clk_clk_con_clk_src_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_clk_con_clk_src_set(&lld, 1U);
    assert(sfr.stCLK_CON.stNative.CLK_SRC == 1U);
}

static void test_lld_clk_clk_status_clk_ready_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_STATUS.stNative.CLK_READY = 1U;
    assert(lld_clk_clk_status_clk_ready_get(&lld) == 1U);
}

static void test_lld_clk_clk_status_clk_stable_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stCLK_STATUS.stNative.CLK_STABLE = 1U;
    assert(lld_clk_clk_status_clk_stable_get(&lld) == 1U);
}

static void test_lld_clk_div_con_div_frac_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stDIV_CON.stNative.DIV_FRAC = 1U;
    assert(lld_clk_div_con_div_frac_get(&lld) == 1U);
}

static void test_lld_clk_div_con_div_frac_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_div_con_div_frac_set(&lld, 1U);
    assert(sfr.stDIV_CON.stNative.DIV_FRAC == 1U);
}

static void test_lld_clk_div_con_div_mode_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stDIV_CON.stNative.DIV_MODE = 1U;
    assert(lld_clk_div_con_div_mode_get(&lld) == 1U);
}

static void test_lld_clk_div_con_div_prediv_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stDIV_CON.stNative.DIV_PREDIV = 1U;
    assert(lld_clk_div_con_div_prediv_get(&lld) == 1U);
}

static void test_lld_clk_div_con_div_prediv_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_div_con_div_prediv_set(&lld, 1U);
    assert(sfr.stDIV_CON.stNative.DIV_PREDIV == 1U);
}

static void test_lld_clk_irq_con_irq_clr_irq_enable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_clr_irq_enable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_CLR == 1U);
}

static void test_lld_clk_irq_con_irq_clr_irq_disable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_CLR = 1U;
    lld_clk_irq_con_irq_clr_irq_disable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_CLR == 0U);
}

static void test_lld_clk_irq_con_irq_clr_irq_status(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_CLR = 1U;
    assert(lld_clk_irq_con_irq_clr_irq_status(&lld) != 0U);
}

static void test_lld_clk_irq_con_irq_clr_irq_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_clr_irq_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_CLR == 1U);
}

static void test_lld_clk_irq_con_irq_en_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_EN = 1U;
    assert(lld_clk_irq_con_irq_en_get(&lld) == 1U);
}

static void test_lld_clk_irq_con_irq_en_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_en_set(&lld, 1U);
    assert(sfr.stIRQ_CON.stNative.IRQ_EN == 1U);
}

static void test_lld_clk_irq_con_irq_en_irq_enable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_en_irq_enable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_EN == 1U);
}

static void test_lld_clk_irq_con_irq_en_irq_disable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_EN = 1U;
    lld_clk_irq_con_irq_en_irq_disable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_EN == 0U);
}

static void test_lld_clk_irq_con_irq_en_irq_status(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_EN = 1U;
    assert(lld_clk_irq_con_irq_en_irq_status(&lld) != 0U);
}

static void test_lld_clk_irq_con_irq_en_irq_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_en_irq_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_EN == 1U);
}

static void test_lld_clk_irq_con_irq_mask_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_MASK = 1U;
    assert(lld_clk_irq_con_irq_mask_get(&lld) == 1U);
}

static void test_lld_clk_irq_con_irq_mask_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_mask_set(&lld, 1U);
    assert(sfr.stIRQ_CON.stNative.IRQ_MASK == 1U);
}

static void test_lld_clk_irq_con_irq_mask_irq_enable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_mask_irq_enable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_MASK == 1U);
}

static void test_lld_clk_irq_con_irq_mask_irq_disable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_MASK = 1U;
    lld_clk_irq_con_irq_mask_irq_disable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_MASK == 0U);
}

static void test_lld_clk_irq_con_irq_mask_irq_status(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_MASK = 1U;
    assert(lld_clk_irq_con_irq_mask_irq_status(&lld) != 0U);
}

static void test_lld_clk_irq_con_irq_mask_irq_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_mask_irq_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_MASK == 1U);
}

static void test_lld_clk_irq_con_irq_pending_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_PENDING = 1U;
    assert(lld_clk_irq_con_irq_pending_get(&lld) == 1U);
}

static void test_lld_clk_irq_con_irq_pending_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_pending_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_PENDING == 1U); /* W1C: must write 1 */
}

static void test_lld_clk_irq_con_irq_pending_irq_enable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_pending_irq_enable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_PENDING == 1U);
}

static void test_lld_clk_irq_con_irq_pending_irq_disable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_PENDING = 1U;
    lld_clk_irq_con_irq_pending_irq_disable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_PENDING == 0U);
}

static void test_lld_clk_irq_con_irq_pending_irq_status(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_PENDING = 1U;
    assert(lld_clk_irq_con_irq_pending_irq_status(&lld) != 0U);
}

static void test_lld_clk_irq_con_irq_pending_irq_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_pending_irq_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_PENDING == 1U);
}

static void test_lld_clk_irq_con_irq_pol_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_POL = 1U;
    assert(lld_clk_irq_con_irq_pol_get(&lld) == 1U);
}

static void test_lld_clk_irq_con_irq_pol_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_pol_set(&lld, 1U);
    assert(sfr.stIRQ_CON.stNative.IRQ_POL == 1U);
}

static void test_lld_clk_irq_con_irq_pol_irq_enable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_pol_irq_enable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_POL == 1U);
}

static void test_lld_clk_irq_con_irq_pol_irq_disable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_POL = 1U;
    lld_clk_irq_con_irq_pol_irq_disable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_POL == 0U);
}

static void test_lld_clk_irq_con_irq_pol_irq_status(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_POL = 1U;
    assert(lld_clk_irq_con_irq_pol_irq_status(&lld) != 0U);
}

static void test_lld_clk_irq_con_irq_pol_irq_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_pol_irq_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_POL == 1U);
}

static void test_lld_clk_irq_con_irq_trig_irq_enable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_trig_irq_enable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_TRIG == 1U);
}

static void test_lld_clk_irq_con_irq_trig_irq_disable(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_TRIG = 1U;
    lld_clk_irq_con_irq_trig_irq_disable(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_TRIG == 0U);
}

static void test_lld_clk_irq_con_irq_trig_irq_status(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stIRQ_CON.stNative.IRQ_TRIG = 1U;
    assert(lld_clk_irq_con_irq_trig_irq_status(&lld) != 0U);
}

static void test_lld_clk_irq_con_irq_trig_irq_clear(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_irq_con_irq_trig_irq_clear(&lld);
    assert(sfr.stIRQ_CON.stNative.IRQ_TRIG == 1U);
}

static void test_lld_clk_pll_ctrl_pll_div_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stPLL_CTRL.stNative.PLL_DIV = 1U;
    assert(lld_clk_pll_ctrl_pll_div_get(&lld) == 1U);
}

static void test_lld_clk_pll_ctrl_pll_div_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_pll_ctrl_pll_div_set(&lld, 1U);
    assert(sfr.stPLL_CTRL.stNative.PLL_DIV == 1U);
}

static void test_lld_clk_pll_ctrl_pll_en_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stPLL_CTRL.stNative.PLL_EN = 1U;
    assert(lld_clk_pll_ctrl_pll_en_get(&lld) == 1U);
}

static void test_lld_clk_pll_ctrl_pll_en_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_pll_ctrl_pll_en_set(&lld, 1U);
    assert(sfr.stPLL_CTRL.stNative.PLL_EN == 1U);
}

static void test_lld_clk_pll_ctrl_pll_lock_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stPLL_CTRL.stNative.PLL_LOCK = 1U;
    assert(lld_clk_pll_ctrl_pll_lock_get(&lld) == 1U);
}

static void test_lld_clk_pll_ctrl_pll_sel_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stPLL_CTRL.stNative.PLL_SEL = 1U;
    assert(lld_clk_pll_ctrl_pll_sel_get(&lld) == 1U);
}

static void test_lld_clk_pll_ctrl_pll_sel_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_pll_ctrl_pll_sel_set(&lld, 1U);
    assert(sfr.stPLL_CTRL.stNative.PLL_SEL == 1U);
}

static void test_lld_clk_reset_con_rst_hw_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRESET_CON.stNative.RST_HW = 1U;
    assert(lld_clk_reset_con_rst_hw_get(&lld) == 1U);
}

static void test_lld_clk_reset_con_rst_hw_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_reset_con_rst_hw_set(&lld, 1U);
    assert(sfr.stRESET_CON.stNative.RST_HW == 1U);
}

static void test_lld_clk_reset_con_rst_stat_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRESET_CON.stNative.RST_STAT = 1U;
    assert(lld_clk_reset_con_rst_stat_get(&lld) == 1U);
}

static void test_lld_clk_reset_con_rst_sw_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRESET_CON.stNative.RST_SW = 1U;
    assert(lld_clk_reset_con_rst_sw_get(&lld) == 1U);
}

static void test_lld_clk_reset_con_rst_sw_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_reset_con_rst_sw_set(&lld, 1U);
    assert(sfr.stRESET_CON.stNative.RST_SW == 1U);
}

static void test_lld_clk_rst_con_clk_bypass_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRST_CON.stNative.CLK_BYPASS = 1U;
    assert(lld_clk_rst_con_clk_bypass_get(&lld) == 1U);
}

static void test_lld_clk_rst_con_clk_bypass_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_rst_con_clk_bypass_set(&lld, 1U);
    assert(sfr.stRST_CON.stNative.CLK_BYPASS == 1U);
}

static void test_lld_clk_rst_con_rst_cnt_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRST_CON.stNative.RST_CNT = 1U;
    assert(lld_clk_rst_con_rst_cnt_get(&lld) == 1U);
}

static void test_lld_clk_rst_con_rst_cnt_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_rst_con_rst_cnt_set(&lld, 1U);
    assert(sfr.stRST_CON.stNative.RST_CNT == 1U);
}

static void test_lld_clk_rst_con_rst_mode_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRST_CON.stNative.RST_MODE = 1U;
    assert(lld_clk_rst_con_rst_mode_get(&lld) == 1U);
}

static void test_lld_clk_rst_con_rst_mode_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_rst_con_rst_mode_set(&lld, 1U);
    assert(sfr.stRST_CON.stNative.RST_MODE == 1U);
}

static void test_lld_clk_rst_con_rst_type_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stRST_CON.stNative.RST_TYPE = 1U;
    assert(lld_clk_rst_con_rst_type_get(&lld) == 1U);
}

static void test_lld_clk_rst_con_rst_type_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_rst_con_rst_type_set(&lld, 1U);
    assert(sfr.stRST_CON.stNative.RST_TYPE == 1U);
}

static void test_lld_clk_spread_con_ss_combined_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stSPREAD_CON.stNative.SS_COMBINED = 1U;
    assert(lld_clk_spread_con_ss_combined_get(&lld) == 1U);
}

static void test_lld_clk_spread_con_ss_combined_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_spread_con_ss_combined_set(&lld, 1U);
    assert(sfr.stSPREAD_CON.stNative.SS_COMBINED == 1U);
}

static void test_lld_clk_spread_con_ss_depth_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stSPREAD_CON.stNative.SS_DEPTH = 1U;
    assert(lld_clk_spread_con_ss_depth_get(&lld) == 1U);
}

static void test_lld_clk_spread_con_ss_depth_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_spread_con_ss_depth_set(&lld, 1U);
    assert(sfr.stSPREAD_CON.stNative.SS_DEPTH == 1U);
}

static void test_lld_clk_spread_con_ss_en_get(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    sfr.stSPREAD_CON.stNative.SS_EN = 1U;
    assert(lld_clk_spread_con_ss_en_get(&lld) == 1U);
}

static void test_lld_clk_spread_con_ss_en_set(void) {
    SFR_CLK sfr = {{0}};
    struct lld_clk lld = { .pSFR = &sfr };
    lld_clk_spread_con_ss_en_set(&lld, 1U);
    assert(sfr.stSPREAD_CON.stNative.SS_EN == 1U);
}

int main(void) {
    test_lld_clk_clk_con_clk_div_get();
    test_lld_clk_clk_con_clk_div_set();
    test_lld_clk_clk_con_clk_en_get();
    test_lld_clk_clk_con_clk_en_set();
    test_lld_clk_clk_con_clk_gate_get();
    test_lld_clk_clk_con_clk_gate_set();
    test_lld_clk_clk_con_clk_mode_get();
    test_lld_clk_clk_con_clk_src_get();
    test_lld_clk_clk_con_clk_src_set();
    test_lld_clk_clk_status_clk_ready_get();
    test_lld_clk_clk_status_clk_stable_get();
    test_lld_clk_div_con_div_frac_get();
    test_lld_clk_div_con_div_frac_set();
    test_lld_clk_div_con_div_mode_get();
    test_lld_clk_div_con_div_prediv_get();
    test_lld_clk_div_con_div_prediv_set();
    test_lld_clk_irq_con_irq_clr_irq_enable();
    test_lld_clk_irq_con_irq_clr_irq_disable();
    test_lld_clk_irq_con_irq_clr_irq_status();
    test_lld_clk_irq_con_irq_clr_irq_clear();
    test_lld_clk_irq_con_irq_en_get();
    test_lld_clk_irq_con_irq_en_set();
    test_lld_clk_irq_con_irq_en_irq_enable();
    test_lld_clk_irq_con_irq_en_irq_disable();
    test_lld_clk_irq_con_irq_en_irq_status();
    test_lld_clk_irq_con_irq_en_irq_clear();
    test_lld_clk_irq_con_irq_mask_get();
    test_lld_clk_irq_con_irq_mask_set();
    test_lld_clk_irq_con_irq_mask_irq_enable();
    test_lld_clk_irq_con_irq_mask_irq_disable();
    test_lld_clk_irq_con_irq_mask_irq_status();
    test_lld_clk_irq_con_irq_mask_irq_clear();
    test_lld_clk_irq_con_irq_pending_get();
    test_lld_clk_irq_con_irq_pending_clear();
    test_lld_clk_irq_con_irq_pending_irq_enable();
    test_lld_clk_irq_con_irq_pending_irq_disable();
    test_lld_clk_irq_con_irq_pending_irq_status();
    test_lld_clk_irq_con_irq_pending_irq_clear();
    test_lld_clk_irq_con_irq_pol_get();
    test_lld_clk_irq_con_irq_pol_set();
    test_lld_clk_irq_con_irq_pol_irq_enable();
    test_lld_clk_irq_con_irq_pol_irq_disable();
    test_lld_clk_irq_con_irq_pol_irq_status();
    test_lld_clk_irq_con_irq_pol_irq_clear();
    test_lld_clk_irq_con_irq_trig_irq_enable();
    test_lld_clk_irq_con_irq_trig_irq_disable();
    test_lld_clk_irq_con_irq_trig_irq_status();
    test_lld_clk_irq_con_irq_trig_irq_clear();
    test_lld_clk_pll_ctrl_pll_div_get();
    test_lld_clk_pll_ctrl_pll_div_set();
    test_lld_clk_pll_ctrl_pll_en_get();
    test_lld_clk_pll_ctrl_pll_en_set();
    test_lld_clk_pll_ctrl_pll_lock_get();
    test_lld_clk_pll_ctrl_pll_sel_get();
    test_lld_clk_pll_ctrl_pll_sel_set();
    test_lld_clk_reset_con_rst_hw_get();
    test_lld_clk_reset_con_rst_hw_set();
    test_lld_clk_reset_con_rst_stat_get();
    test_lld_clk_reset_con_rst_sw_get();
    test_lld_clk_reset_con_rst_sw_set();
    test_lld_clk_rst_con_clk_bypass_get();
    test_lld_clk_rst_con_clk_bypass_set();
    test_lld_clk_rst_con_rst_cnt_get();
    test_lld_clk_rst_con_rst_cnt_set();
    test_lld_clk_rst_con_rst_mode_get();
    test_lld_clk_rst_con_rst_mode_set();
    test_lld_clk_rst_con_rst_type_get();
    test_lld_clk_rst_con_rst_type_set();
    test_lld_clk_spread_con_ss_combined_get();
    test_lld_clk_spread_con_ss_combined_set();
    test_lld_clk_spread_con_ss_depth_get();
    test_lld_clk_spread_con_ss_depth_set();
    test_lld_clk_spread_con_ss_en_get();
    test_lld_clk_spread_con_ss_en_set();
    return 0;
}
