"""
pr_stage.py -- PR Staging Module

On compile success, produces the following artifacts and stages them via git add:
    - lld.h             patched in-place, verified by gcc
    - test_lld_generated.c  auto unit tests for all new/changed functions
    - PR_DESCRIPTION.md change table with register, field, change type,
                        LLM used flag, test result, and manual review checklist

The PR description includes a git diff --stat of lld.h and a list of all
added and removed function names for a self-contained review.
"""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from lld_gen.sfr_diff_analyzer import ChangeRecord, ChangeType
from lld_gen.compile_check import CompileResult


_PR_TEMPLATE = """\
# LLD Auto-Patcher PR -- {ip} ({date})

## Change Summary

| Register | Field | Change Type | LLM Used | Test Result | Review Flag |
|----------|-------|-------------|----------|-------------|-------------|
{rows}

## Files Changed

- `{lld_file}` -- patched in-place, verified by gcc
- `{test_file}` -- auto-generated unit tests
- `sfr_new.h` -- new SFR header baseline

## Function Delta

### Added / Updated Functions
```
{added_fns}
```

### Removed Functions
```
{removed_fns}
```

{deprecated_section}

## Git Diff Stat

```
{diff_stat}
```

## Manual Review Checklist

{checklist}

## GitHub PR

{github_pr_section}

---
*Generated by lld_gen v1.0 -- Samsung SSRI CXL Architecture & Security IP Division*
"""

_REVIEW_ITEM = "- [ ] **{fn}** -- {reason}"


def _git_diff_stat(path: str | Path) -> str:
    try:
        result = subprocess.run(
            ["git", "diff", "--stat", str(path)],
            capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip() or "(no staged changes)"
    except Exception:
        return "(git diff unavailable)"


def _git_add(*paths: str | Path) -> bool:
    try:
        result = subprocess.run(
            ["git", "add"] + [str(p) for p in paths],
            capture_output=True, text=True, timeout=10
        )
        return result.returncode == 0
    except Exception:
        return False


def _get_github_url(configured_url: str = "") -> str:
    """
    Return the GitHub repo URL.
    Priority: 1) configured_url from config/CLI  2) git remote origin  3) empty
    """
    if configured_url:
        return configured_url.rstrip("/")
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5
        )
        url = result.stdout.strip()
        # Normalise SSH -> HTTPS:  git@github.com:user/repo.git -> https://github.com/user/repo
        if url.startswith("git@github.com:"):
            url = "https://github.com/" + url[len("git@github.com:"):]
        return url.removesuffix(".git")
    except Exception:
        return ""


def _make_pr_section(github_url: str, ip: str, branch: str = "") -> str:
    """Build the GitHub PR section of the description."""
    if not github_url:
        return (
            "No GitHub URL configured.\n"
            "Add `github_url` to lld_patcher.yaml or set git remote origin, then run:\n"
            "```\n"
            "git push origin <branch>\n"
            "# Open: https://github.com/<user>/<repo>/compare/<branch>\n"
            "```"
        )

    # Try to get current branch
    if not branch:
        try:
            r = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True, text=True, timeout=5
            )
            branch = r.stdout.strip() or "main"
        except Exception:
            branch = "main"

    repo_url   = github_url
    pr_url     = f"{repo_url}/compare/{branch}?expand=1"
    push_cmd   = f"git push origin {branch}"

    return (
        f"**Repository**: {repo_url}\n"
        f"**Branch**    : `{branch}`\n\n"
        f"**Step 1 -- Push the branch:**\n"
        f"```bash\n"
        f"{push_cmd}\n"
        f"```\n\n"
        f"**Step 2 -- Open PR on GitHub:**\n"
        f"```\n"
        f"{pr_url}\n"
        f"```\n\n"
        f"Or click: [{repo_url.split('/')[-1]} -- Create PR]({pr_url})"
    )


def build_pr_description(
    ip:              str,
    changes:         List[ChangeRecord],
    compile_result:  CompileResult,
    lld_file:        str | Path,
    test_file:       str | Path,
    added_fns:       Optional[List[str]] = None,
    removed_fns:     Optional[List[str]] = None,
    deprecated_fns:  Optional[List[str]] = None,
    github_url:      str = "",
) -> str:
    """Build the PR_DESCRIPTION.md content."""
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Build change table rows
    rows: List[str] = []
    for cr in changes:
        if cr.change_type == ChangeType.UNCHANGED:
            continue
        llm_used = "yes" if cr.needs_llm else "--"
        fn_failed = any(
            (cr.field_name or "").upper() in fn.upper()
            for fn in (compile_result.needs_review or [])
        )
        test_result = "MANUAL" if fn_failed else ("PASS" if compile_result.success else "FAIL")
        review_flag = "REVIEW" if fn_failed else ""
        rows.append(
            f"| {cr.reg_name} | {cr.field_name or '--'} | "
            f"`{cr.change_type}` | {llm_used} | {test_result} | {review_flag} |"
        )

    if not rows:
        rows = ["| -- | -- | No changes detected | -- | -- | -- |"]

    # Checklist for manual review items
    checklist_items: List[str] = []
    for fn in (compile_result.needs_review or []):
        if fn == "<compile_check_unavailable>":
            checklist_items.append(
                "- [ ] Compile check was skipped (gcc not found). "
                "Verify generated code manually before merging."
            )
        else:
            checklist_items.append(
                _REVIEW_ITEM.format(fn=fn, reason="Failed gcc after 3 LLM retries")
            )
    if not checklist_items:
        checklist_items = ["- [x] All functions pass gcc compile check"]

    # Deprecated functions section
    if deprecated_fns:
        dep_lines = [
            "## ⚠ Deprecated LLD Functions (Manual Deletion Required)",
            "",
            "The following functions reference SFR registers that were **deleted** in the",
            "new SFR version. They are kept in the LLD to avoid compilation errors in IP",
            "emulation files.",
            "",
            "**Action required:** Search for callers of these functions, then delete them",
            "in a follow-up PR once all callers are removed.",
            "",
        ]
        for fn in deprecated_fns:
            dep_lines.append(f"- `{fn}()`")
        deprecated_section = "\n".join(dep_lines)
    else:
        deprecated_section = ""

    diff_stat  = _git_diff_stat(lld_file)
    gh_url     = _get_github_url(github_url)
    pr_section = _make_pr_section(gh_url, ip)

    return _PR_TEMPLATE.format(
        ip=ip.upper(),
        date=date,
        rows="\n".join(rows),
        lld_file=Path(lld_file).name,
        test_file=Path(test_file).name,
        added_fns="\n".join(added_fns or ["(none)"]),
        removed_fns="\n".join(removed_fns or ["(none)"]),
        deprecated_section=deprecated_section,
        diff_stat=diff_stat,
        checklist="\n".join(checklist_items),
        github_pr_section=pr_section,
    )


def stage_pr(
    ip:              str,
    changes:         List[ChangeRecord],
    compile_result:  CompileResult,
    lld_file:        str | Path,
    test_file:       str | Path,
    sfr_new:         str | Path,
    out_dir:         Optional[str | Path] = None,
    added_fns:       Optional[List[str]] = None,
    removed_fns:     Optional[List[str]] = None,
    deprecated_fns:  Optional[List[str]] = None,
    no_git:          bool = False,
    github_url:      str = "",
) -> Path:
    """
    Generate PR_DESCRIPTION.md and git add all changed files.

    Args:
        ip:             Peripheral IP name
        changes:        Classified change list
        compile_result: Result from run_compile_check()
        lld_file:       Path to patched lld.h
        test_file:      Path to test_lld_generated.c
        sfr_new:        Path to new sfr.h
        out_dir:        Directory for PR_DESCRIPTION.md; defaults to lld_file parent
        added_fns:      List of newly generated function names
        removed_fns:    List of removed function names
        no_git:         If True, skip git add
        github_url:     GitHub repo URL (auto-detected from git remote if empty)

    Returns:
        Path to PR_DESCRIPTION.md
    """
    lld_file  = Path(lld_file)
    test_file = Path(test_file)
    sfr_new   = Path(sfr_new)
    out_dir   = Path(out_dir) if out_dir else lld_file.parent

    gh_url = _get_github_url(github_url)

    pr_desc = build_pr_description(
        ip=ip, changes=changes, compile_result=compile_result,
        lld_file=lld_file, test_file=test_file,
        added_fns=added_fns, removed_fns=removed_fns,
        deprecated_fns=deprecated_fns,
        github_url=gh_url,
    )

    pr_path = out_dir / "PR_DESCRIPTION.md"
    pr_path.write_text(pr_desc, encoding="utf-8")
    print(f"  [PR] PR_DESCRIPTION.md -> {pr_path}")

    if gh_url:
        print(f"  [PR] GitHub repo : {gh_url}")
        # Print the direct PR creation URL
        try:
            r = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True, text=True, timeout=5
            )
            branch = r.stdout.strip() or "main"
        except Exception:
            branch = "main"
        print(f"  [PR] Create PR   : {gh_url}/compare/{branch}?expand=1")

    if not no_git:
        files_to_stage = [lld_file, test_file, sfr_new, pr_path]
        ok = _git_add(*files_to_stage)
        if ok:
            print(f"  [PR] git add: {', '.join(str(f.name) for f in files_to_stage)}")
        else:
            print("  [PR] WARNING: git add failed -- stage files manually.")

    return pr_path
