"""
pr_stage.py — PR Staging Module

On compile success, produces the following artifacts and stages them via git add:
    - lld.h             patched in-place, verified by gcc
    - test_lld_generated.c  auto unit tests for all new/changed functions
    - PR_DESCRIPTION.md change table with register, field, change type,
                        LLM used flag, test result, and manual review checklist

The PR description includes a git diff --stat of lld.h and a list of all
added and removed function names for a self-contained review.
"""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from lld_gen.sfr_diff_analyzer import ChangeRecord, ChangeType
from lld_gen.compile_check import CompileResult


_PR_TEMPLATE = """\
# LLD Auto-Patcher PR — {ip} ({date})

## Change Summary

| Register | Field | Change Type | LLM Used | Test Result | Review Flag |
|----------|-------|-------------|----------|-------------|-------------|
{rows}

## Files Changed

- `{lld_file}` — patched in-place, verified by gcc
- `{test_file}` — auto-generated unit tests
- `sfr_new.h` — new SFR header baseline

## Function Delta

### Added / Updated Functions
```
{added_fns}
```

### Removed Functions
```
{removed_fns}
```

## Git Diff Stat

```
{diff_stat}
```

## Manual Review Checklist

{checklist}

---
*Generated by lld_gen v1.0 — Samsung SSRI CXL Architecture & Security IP Division*
"""

_REVIEW_ITEM = "- [ ] **{fn}** — {reason}"


def _git_diff_stat(path: str | Path) -> str:
    try:
        result = subprocess.run(
            ["git", "diff", "--stat", str(path)],
            capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip() or "(no staged changes)"
    except Exception:
        return "(git diff unavailable)"


def _git_add(*paths: str | Path) -> bool:
    try:
        result = subprocess.run(
            ["git", "add"] + [str(p) for p in paths],
            capture_output=True, text=True, timeout=10
        )
        return result.returncode == 0
    except Exception:
        return False


def build_pr_description(
    ip:            str,
    changes:       List[ChangeRecord],
    compile_result: CompileResult,
    lld_file:      str | Path,
    test_file:     str | Path,
    added_fns:     Optional[List[str]] = None,
    removed_fns:   Optional[List[str]] = None,
) -> str:
    """Build the PR_DESCRIPTION.md content."""
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Build change table rows
    rows: List[str] = []
    for cr in changes:
        if cr.change_type == ChangeType.UNCHANGED:
            continue
        llm_used = "✅" if cr.needs_llm else "—"
        fn_failed = any(
            (cr.field_name or "").upper() in fn.upper()
            for fn in (compile_result.needs_review or [])
        )
        test_result = "⚠️ MANUAL" if fn_failed else ("✅ PASS" if compile_result.success else "❌ FAIL")
        review_flag = "🔴 REVIEW" if fn_failed else ""
        rows.append(
            f"| {cr.reg_name} | {cr.field_name or '—'} | "
            f"`{cr.change_type}` | {llm_used} | {test_result} | {review_flag} |"
        )

    if not rows:
        rows = ["| — | — | No changes detected | — | — | — |"]

    # Checklist for manual review items
    checklist_items: List[str] = []
    for fn in (compile_result.needs_review or []):
        if fn == "<compile_check_unavailable>":
            checklist_items.append(
                "- [ ] ⚠️ Compile check was skipped (gcc not found). "
                "Verify generated code manually before merging."
            )
        else:
            checklist_items.append(
                _REVIEW_ITEM.format(fn=fn, reason="Failed gcc after 3 LLM retries")
            )
    if not checklist_items:
        checklist_items = ["- [x] All functions pass gcc compile check"]

    diff_stat = _git_diff_stat(lld_file)

    return _PR_TEMPLATE.format(
        ip=ip.upper(),
        date=date,
        rows="\n".join(rows),
        lld_file=Path(lld_file).name,
        test_file=Path(test_file).name,
        added_fns="\n".join(added_fns or ["(none)"]),
        removed_fns="\n".join(removed_fns or ["(none)"]),
        diff_stat=diff_stat,
        checklist="\n".join(checklist_items),
    )


def stage_pr(
    ip:            str,
    changes:       List[ChangeRecord],
    compile_result: CompileResult,
    lld_file:      str | Path,
    test_file:     str | Path,
    sfr_new:       str | Path,
    out_dir:       Optional[str | Path] = None,
    added_fns:     Optional[List[str]] = None,
    removed_fns:   Optional[List[str]] = None,
    no_git:        bool = False,
) -> Path:
    """
    Generate PR_DESCRIPTION.md and git add all changed files.

    Args:
        ip:             Peripheral IP name
        changes:        Classified change list
        compile_result: Result from run_compile_check()
        lld_file:       Path to patched lld.h
        test_file:      Path to test_lld_generated.c
        sfr_new:        Path to new sfr.h
        out_dir:        Directory for PR_DESCRIPTION.md; defaults to lld_file parent
        added_fns:      List of newly generated function names
        removed_fns:    List of removed function names
        no_git:         If True, skip git add

    Returns:
        Path to PR_DESCRIPTION.md
    """
    lld_file  = Path(lld_file)
    test_file = Path(test_file)
    sfr_new   = Path(sfr_new)
    out_dir   = Path(out_dir) if out_dir else lld_file.parent

    pr_desc = build_pr_description(
        ip=ip, changes=changes, compile_result=compile_result,
        lld_file=lld_file, test_file=test_file,
        added_fns=added_fns, removed_fns=removed_fns,
    )

    pr_path = out_dir / "PR_DESCRIPTION.md"
    pr_path.write_text(pr_desc, encoding="utf-8")
    print(f"  [PR] PR_DESCRIPTION.md → {pr_path}")

    if not no_git:
        files_to_stage = [lld_file, test_file, sfr_new, pr_path]
        ok = _git_add(*files_to_stage)
        if ok:
            print(f"  [PR] git add: {', '.join(str(f.name) for f in files_to_stage)}")
        else:
            print("  [PR] WARNING: git add failed — stage files manually.")

    return pr_path
