"""
Generates sfr.h from a RegisterMap.

Output structure:
  /* [sfr_gen:reg:begin:CTRL_REG] */
  #define CXL_CTRL_CTRL_REG_OFFSET   0x0000U
  #define CXL_CTRL_CTRL_REG_EN_MASK  0x00000001U
  ...
  /* [sfr_gen:reg:end:CTRL_REG] */

The begin/end sentinel comments are the only markers used — no SHA values
are stored here. Change detection is done entirely by comparing parsed
RegisterMap objects (see updater/diff_engine.py).
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from models import Field, Register, RegisterMap

# Sentinel format — plain register name, no hashes
_REG_BEGIN = "/* [sfr_gen:reg:begin:{name}] */"
_REG_END   = "/* [sfr_gen:reg:end:{name}] */"


def _guard(peripheral: str) -> str:
    return f"{peripheral.upper()}_SFR_H"


def _pfx(peripheral: str, reg_name: str) -> str:
    return f"{peripheral.upper()}_{reg_name.upper()}"


def _field_macros(pfx: str, f: Field) -> str:
    lines = [
        f"#define {pfx}_{f.name}_MSB      {f.msb}",
        f"#define {pfx}_{f.name}_LSB      {f.lsb}",
        f"#define {pfx}_{f.name}_SHIFT    {f.lsb}U",
        f"#define {pfx}_{f.name}_MASK     0x{f.mask:08X}U",
        f"#define {pfx}_{f.name}_RESET    0x{f.reset_value:X}U",
    ]
    return "\n".join(lines)


def _register_block(peripheral: str, reg: Register) -> str:
    pfx = _pfx(peripheral, reg.name)
    sep = "─" * 58
    lines = [
        _REG_BEGIN.format(name=reg.name),
        f"/* {sep}",
        f" * {reg.name}  offset=0x{reg.offset:04X}",
    ]
    if reg.description:
        lines.append(f" * {reg.description}")
    lines.append(" */")
    lines.append(f"#define {pfx}_OFFSET    0x{reg.offset:04X}U")
    lines.append("")

    for f in reg.fields:
        lines.append(
            f"/* {f.name} [{f.msb}:{f.lsb}]  "
            f"access={f.access}  reset=0x{f.reset_value:X} */"
        )
        lines.append(_field_macros(pfx, f))
        lines.append("")

    lines.append(_REG_END.format(name=reg.name))
    return "\n".join(lines)


def generate_sfr(rm: RegisterMap, output_path: Optional[str | Path] = None) -> str:
    """
    Generate full sfr.h content for *rm*.
    Writes to *output_path* if provided and returns the content string.
    """
    guard = _guard(rm.peripheral)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "/*",
        " * AUTO-GENERATED by sfr_gen — DO NOT EDIT",
        f" * Peripheral : {rm.peripheral}",
        f" * Base Addr  : 0x{rm.base_addr:08X}",
        f" * Source     : {Path(rm.source_file).name if rm.source_file else 'N/A'}",
        f" * Generated  : {now}",
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"#define {rm.peripheral.upper()}_BASE    0x{rm.base_addr:08X}UL",
        "",
    ]

    for reg in rm.registers:
        lines.append(_register_block(rm.peripheral, reg))
        lines.append("")

    lines.append(f"#endif /* {guard} */")
    content = "\n".join(lines) + "\n"

    if output_path:
        Path(output_path).write_text(content, encoding="utf-8")

    return content
