"""
generate_pmu_lld.py — Build tests/workspace_demo/lld/lld_pmu.h from old_sfr/sfr_pmu.h

Run from sfr_gen/ directory:
    python tests/workspace_demo/generate_pmu_lld.py

Parses old_sfr/sfr_pmu.h using SfrParser (IP auto-detected from filename),
then generates one LLD register block per register using generate_register_block()
from lld_gen.lld_patcher, and writes a proper C header to lld/lld_pmu.h.

The resulting lld_pmu.h is the BASELINE LLD for the workspace_demo. It can
then be patched by running the full lld_patcher pipeline against new_sfr/sfr_pmu.h.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure project root (sfr_gen/) is on sys.path so lld_gen is importable
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from lld_gen.sfr_diff_analyzer import SfrParser
from lld_gen.lld_patcher import generate_register_block

# ── Paths ──────────────────────────────────────────────────────────────────
WORKSPACE_DIR = Path(__file__).parent          # tests/workspace_demo/
OLD_SFR       = WORKSPACE_DIR / "old_sfr" / "sfr_pmu.h"
LLD_DIR       = WORKSPACE_DIR / "lld"
LLD_OUT       = LLD_DIR / "lld_pmu.h"


def main() -> None:
    # ── Parse old SFR ─────────────────────────────────────────────────────
    print(f"[gen] Parsing {OLD_SFR.relative_to(WORKSPACE_DIR.parent.parent)} ...")
    parser = SfrParser()                       # ip="" → auto-detect from filename
    ir     = parser.parse_file(OLD_SFR)

    ip   = ir.ip
    regs = list(ir.registers.values())

    print(f"[gen] IP detected : {ip}")
    print(f"[gen] Registers   : {[r.name for r in regs]}")
    for r in sorted(regs, key=lambda x: x.offset):
        fields_str = ", ".join(sorted(r.fields))
        print(f"      {r.name:<20} offset=0x{r.offset:04X}  fields=[{fields_str}]")

    # ── Ensure output directory exists ────────────────────────────────────
    LLD_DIR.mkdir(parents=True, exist_ok=True)

    # ── Build header content ──────────────────────────────────────────────
    lines: list[str] = []

    # File-level header comment
    lines += [
        "/* lld_pmu.h -- Auto-generated LLD for PMU",
        " * Generated by: tests/workspace_demo/generate_pmu_lld.py",
        " * Source SFR  : old_sfr/sfr_pmu.h",
        " * DO NOT EDIT -- regenerate with generate_pmu_lld.py",
        " */",
    ]

    # Header guard
    lines += [
        "#ifndef LLD_PMU_H",
        "#define LLD_PMU_H",
        "",
        "#include <stdint.h>",
        '#include "sfr_pmu.h"',
        "",
        "/* === BEGIN LLD_PMU === */",
        "",
    ]

    # One register block per register, sorted by offset
    for reg in sorted(regs, key=lambda r: r.offset):
        block = generate_register_block(ip, reg)
        lines.append(block)

    # Footer
    lines += [
        "/* === END LLD_PMU === */",
        "",
        "#endif /* LLD_PMU_H */",
        "",
    ]

    content = "\n".join(lines)

    # ── Write output ───────────────────────────────────────────────────────
    LLD_OUT.write_text(content, encoding="utf-8")
    print(f"[gen] Written     : {LLD_OUT}")
    print(f"[gen] Size        : {LLD_OUT.stat().st_size} bytes")
    print("[gen] Done.")


if __name__ == "__main__":
    main()
