/* AUTO-GENERATED by lld_gen — DO NOT EDIT */
#include <stdint.h>
#include <assert.h>
#include "sfr_new.h"
#include "lld_patched.h"

static void test_DMA_CTRL_BURST_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[0] = 0x00000002U;
    uint32_t v = (uint32_t)DMA_CTRL_BURST_get(regs);
    assert(v == 1U);
}

static void test_DMA_CTRL_BURST_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[0] = 0xFFFFFFFFU;
    DMA_CTRL_BURST_set(regs, 0U);
    assert((regs[0] & 0x0000001EU) == 0U);
    assert((regs[0] & ~0x0000001EU) == (~0x0000001EU & 0xFFFFFFFFU));
}

static void test_DMA_CTRL_MODE_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[0] = 0x00000010U;
    uint32_t v = (uint32_t)DMA_CTRL_MODE_get(regs);
    assert(v == 1U);
}

static void test_DMA_CTRL_PRIORITY_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[0] = 0x00010000U;
    uint32_t v = (uint32_t)DMA_CTRL_PRIORITY_get(regs);
    assert(v == 1U);
}

static void test_DMA_CTRL_TIMEOUT_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[0] = 0x00000100U;
    uint32_t v = (uint32_t)DMA_CTRL_TIMEOUT_get(regs);
    assert(v == 1U);
}

static void test_DMA_CTRL_TIMEOUT_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[0] = 0xFFFFFFFFU;
    DMA_CTRL_TIMEOUT_set(regs, 0U);
    assert((regs[0] & 0x0000FF00U) == 0U);
    assert((regs[0] & ~0x0000FF00U) == (~0x0000FF00U & 0xFFFFFFFFU));
}

static void test_DMA_STATUS_BUSY_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0x01000000U;
    uint32_t v = (uint32_t)DMA_STATUS_BUSY_get(regs);
    assert(v == 1U);
}

static void test_DMA_STATUS_THRESH_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0x00000200U;
    uint32_t v = (uint32_t)DMA_STATUS_THRESH_get(regs);
    assert(v == 1U);
}

static void test_DMA_STATUS_THRESH_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[1] = 0xFFFFFFFFU;
    DMA_STATUS_THRESH_set(regs, 0U);
    assert((regs[1] & 0x0000FE00U) == 0U);
    assert((regs[1] & ~0x0000FE00U) == (~0x0000FE00U & 0xFFFFFFFFU));
}

static void test_DMA_IRQ_IRQ_EN_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[5] = 0x00000001U;
    uint32_t v = (uint32_t)DMA_IRQ_IRQ_EN_get(regs);
    assert(v == 1U);
}

static void test_DMA_IRQ_IRQ_EN_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[5] = 0xFFFFFFFFU;
    DMA_IRQ_IRQ_EN_set(regs, 0U);
    assert((regs[5] & 0x00000001U) == 0U);
    assert((regs[5] & ~0x00000001U) == (~0x00000001U & 0xFFFFFFFFU));
}

static void test_DMA_IRQ_IRQ_STATUS_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[5] = 0x00000002U;
    uint32_t v = (uint32_t)DMA_IRQ_IRQ_STATUS_get(regs);
    assert(v == 1U);
}

static void test_DMA_IRQ_IRQ_STATUS_clear(void) {
    volatile uint32_t regs[256] = {0};
    DMA_IRQ_IRQ_STATUS_clear(regs);
    assert(regs[5] == 0x000000FEU);
}

static void test_DMA_IRQ_IRQ_MASK_get(void) {
    volatile uint32_t regs[256] = {0};
    regs[5] = 0x00000100U;
    uint32_t v = (uint32_t)DMA_IRQ_IRQ_MASK_get(regs);
    assert(v == 1U);
}

static void test_DMA_IRQ_IRQ_MASK_set(void) {
    volatile uint32_t regs[256] = {0};
    regs[5] = 0xFFFFFFFFU;
    DMA_IRQ_IRQ_MASK_set(regs, 0U);
    assert((regs[5] & 0x0000FF00U) == 0U);
    assert((regs[5] & ~0x0000FF00U) == (~0x0000FF00U & 0xFFFFFFFFU));
}

int main(void) {
    test_DMA_CTRL_BURST_get();
    test_DMA_CTRL_MODE_get();
    test_DMA_CTRL_PRIORITY_get();
    test_DMA_CTRL_TIMEOUT_get();
    test_DMA_STATUS_BUSY_get();
    test_DMA_STATUS_THRESH_get();
    test_DMA_IRQ_IRQ_EN_get();
    test_DMA_IRQ_IRQ_STATUS_get();
    test_DMA_IRQ_IRQ_MASK_get();
    return 0;
}
